import Head from 'next/head'
import classes from "./index.module.scss"
import Navbar from '@/components/navbar'
import Animation from '@/components/animation/index'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Resume by Miki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/duck.png" />
      </Head>

      <main >
        <Navbar />
        <div className={classes.main} >
          <div className={classes.animation}></div>
          <p className={classes.test}>test scss</p>
          <Animation />
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
          <p className='text-red'>test tail wind</p>
        </div>
      </main>
    </div>
  )
}


