import Head from 'next/head'
import classes from "./index.module.scss"
import Navbar from '@/components/navbar'
import Animation from '@/components/animation/index'
import { useEffect, useMemo, useState } from "react";



//paralaxx animation 
export default function Home() {
  const [ScrollY, setScrollY] = useState(0);

  useEffect(() => {
    const handleScroll = () => {
      //window.scrolly เอาไว้เช็คตำเเหน่งที่ scroll เเนวตั้ง
      setScrollY(window.scrollY);
    };
    //เช็ค scroll ในครั้งเเรกที่หน้าเว็ปถูกโหลดขึ้นมา(didmounth)
    handleScroll();

    //set ค่าใน handleScroll ระหว่างที่ scroll mouse อยู่
    window.addEventListener("scroll", handleScroll);

    //set ค่าใน handleScroll ตอนที่ scroll mouse หยุด
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  //เอาค่าตัวเลขของ scroll มาคำนวณเพื่อลดขนาดของ css <ตรงนี้อิงตาม width>
  const setSizeImg = useMemo(() => {
    // clamp คือฟังชั้นที่เอาไว้คำนวณเพื่อนำค่าที่ได้ไปเก็บใน ScrollY <getter setter ที่สร้างมา>
    return clamp(300 - (ScrollY / 2), 300, 250);
  }, [ScrollY])

  function clamp(size: number, max: number, min: number) {
    return size <= min
      ? min
      : size >= max
        ? max
        : size

  }

  return (
    <div>
      <Head>
        <title>Resume by Miki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/profile.svg" />
      </Head>

      <main >
        <Navbar />
        <div className={classes.main} >
          <Animation />
        </div>
        <div className={classes.recommand} id='Recommend'>
          <img src="./profile.svg" alt="test" style={{ width: setSizeImg,zIndex:1 }} />
          <p className={classes.hello}>Hi!, My name is peeranut moonrut.</p>
          <p className={classes.bio}>I'm want practic everything if I can.</p>
        </div>
        <div className={classes.recommand} id='Education'>
          <p className={classes.greeting}>Hi, My name is peeranut moonrut!</p>
        </div>
      </main>
    </div>
  )
}


